MinerU:
  API: eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJqdGkiOiI1MDE1ODI0NiIsInJvbCI6IlJPTEVfUkVHSVNURVIiLCJpc3MiOiJPcGVuWExhYiIsImlhdCI6MTc3MTcyNDYxMywiY2xpZW50SWQiOiJsa3pkeDU3bnZ5MjJqa3BxOXgydyIsInBob25lIjoiIiwib3BlbklkIjpudWxsLCJ1dWlkIjoiNTNiMzdmMzYtOGExZS00MWZhLWFiOTAtN2M5ODAwZDRjZmI4IiwiZW1haWwiOiIiLCJleHAiOjE3Nzk1MDA2MTN9.zBhAgS9NBfQoqQKfadQEdbMTXigtcPY8gFm6XCCjCnJuLBQEh41QOOOdihqpyJAos_lbnfaqFceQ4Xm74_uwNA

  

qwen3:
  url: https://dashscope.aliyuncs.com/compatible-mode/v1
  keys: sk-86a160d9b1044caba0c1f123e1f8f8e0
  models: [qwen3-max]

